In [43]:
import random
import pandas as pd
import pyterrier as pt 
from pyterrier.measures import *
import os
from pathlib import *
import json
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)

/sw/arcts/centos7/python3.6-anaconda/5.2.0/lib/python3.6/site-packages/ipykernel_launcher.py:13: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  del sys.path[0]

In [51]:
cwd = Path(os.getcwd())
path_dataset = os.path.join(cwd.parent.absolute(),'dataset')
path_data_txt = os.path.join(path_dataset, 'data_txt')
path_data_json = os.path.join(path_dataset, 'data_json')

def JsontoDataFrame(profiles_json, split=True):
    rows = []
    docno = 0
    for profile in profiles_json:
        meta_data = {
            "education": json.dumps(profile["Education"]),
            "company": None,
            "title": None,
            "period": None,
        }
        for expBlock in profile["Experience"]:
            meta_data["company"] = expBlock["company"]
            meta_data["title"]   = expBlock["title"]
            meta_data["period"]  = expBlock["period"]
            if expBlock["description"]:
                bulletpoints = expBlock["description"].split('\n') if split else [expBlock["description"]]
                for bulletpoint in bulletpoints:
                    if len(bulletpoint.split()) >= 5:
                        row = [str(docno),bulletpoint]
                        for item in meta_data.values():
                            row.append(item)
                        rows.append(row)
                        docno += 1
    docs_df =   pd.DataFrame(rows,columns= ['docno','text']+list(meta_data.keys()) )
    return docs_df
            
# get raw json files & preprocess
profiles_json = []
for filename in os.listdir(path_data_json):
    path_profile  = os.path.join( path_data_json, filename  )
    with open(path_profile) as ptr:
        profile_json = json.load(ptr)
        profiles_json.append(profile_json)
print(len(profiles_json))
profiles = JsontoDataFrame(profiles_json)
profiles[:10]
        
### buildjson('bullet_points', path_dataset,doc_ls)

39

,docno,text,education,company,title,period
0,0,"• Work with OS and device driver vendors in Taiwan, China, India and other global offices to develop, debug and handle system software issues by analyzing dump files and using programming tool to change configuration settings for major notebook manufacturing clients, such as Lenovo","[{""school"": ""University of Southern California"", ""degree"": ""Master of Science - MS"", ""major"": ""Computer Science"", ""period"": ""2021 \u2013 2023""}, {""school"": ""Czech Technical University in Prague"", ""degree"": ""Exchange student"", ""major"": ""Industrial Engineering"", ""period"": ""2018 \u2013 2018""}, {""school"": ""National Taipei University of Technology"", ""degree"": ""Bachelor of Science - BS"", ""major"": ""Industrial Engineering"", ""period"": ""2014 \u2013 2018""}]",Wistron Full-time,Software Engineer,Aug 2019 – May 2021
1,1,• Utilized ASP.Net and MySQL to support Cloud-based Enterprise Resource Planning (ERP) system development,"[{""school"": ""University of Southern California"", ""degree"": ""Master of Science - MS"", ""major"": ""Computer Science"", ""period"": ""2021 \u2013 2023""}, {""school"": ""Czech Technical University in Prague"", ""degree"": ""Exchange student"", ""major"": ""Industrial Engineering"", ""period"": ""2018 \u2013 2018""}, {""school"": ""National Taipei University of Technology"", ""degree"": ""Bachelor of Science - BS"", ""major"": ""Industrial Engineering"", ""period"": ""2014 \u2013 2018""}]",TopOne Information Full-time,Software Developer,Jul 2018 – Jul 2019
2,2,"• Worked with UI/UX designers to redesign and improve user experience for Web-based ERP systems by unifying the buttons, layout and UI flow across each function","[{""school"": ""University of Southern California"", ""degree"": ""Master of Science - MS"", ""major"": ""Computer Science"", ""period"": ""2021 \u2013 2023""}, {""school"": ""Czech Technical University in Prague"", ""degree"": ""Exchange student"", ""major"": ""Industrial Engineering"", ""period"": ""2018 \u2013 2018""}, {""school"": ""National Taipei University of Technology"", ""degree"": ""Bachelor of Science - BS"", ""major"": ""Industrial Engineering"", ""period"": ""2014 \u2013 2018""}]",TopOne Information Full-time,Software Developer,Jul 2018 – Jul 2019
3,3,"• Reports Creation – Retrieved data and created clear and effective reports, including quotes, customer orders, stock tracking, BOM lists, etc. for client needs in different industries","[{""school"": ""University of Southern California"", ""degree"": ""Master of Science - MS"", ""major"": ""Computer Science"", ""period"": ""2021 \u2013 2023""}, {""school"": ""Czech Technical University in Prague"", ""degree"": ""Exchange student"", ""major"": ""Industrial Engineering"", ""period"": ""2018 \u2013 2018""}, {""school"": ""National Taipei University of Technology"", ""degree"": ""Bachelor of Science - BS"", ""major"": ""Industrial Engineering"", ""period"": ""2014 \u2013 2018""}]",TopOne Information Full-time,Software Developer,Jul 2018 – Jul 2019
4,4,"• Maintained regression test routine, including improved testing scrips, added new test cases, and updated baselines from different operating systems.","[{""school"": ""UC Irvine"", ""degree"": ""Master of Computer Science - MCS"", ""major"": ""Computer Science"", ""period"": ""2020 \u2013 2021""}, {""school"": ""Texas A&M University"", ""degree"": ""Bachelor of Science - BS"", ""major"": ""Major: Applied Mathematics - Minor: Computer Sience"", ""period"": ""2016 \u2013 2020""}]",Divergent Internship,"Testing And Software Engineer, Summer Intern",Jun 2021 – Sep 2021
5,5,• Improved code coverage rate from 30% to 72% by tripling the number of tests to cover more code branches and detecting more than 200+ lines of dead codes from team project.,"[{""school"": ""UC Irvine"", ""degree"": ""Master of Computer Science - MCS"", ""major"": ""Computer Science"", ""period"": ""2020 \u2013 2021""}, {""school"": ""Texas A&M University"", ""degree"": ""Bachelor of Science - BS"", ""major"": ""Major: Applied Mathematics - Minor: Computer Sience"", ""period"": ""2016 \u2013 2020""}]",Divergent Internship,"Testing And Software Engineer, Summer Intern",Jun 2021 – Sep 2021
6,6,"• Helped migrating team project’s build from gcc to Intel compiler icc/icpc. Managed all c++ third-party libraries by using Conan, adapted cross-building strategy and solved in-capabilities among packages from different compiler.","[{""school"": ""UC Irvine"", ""degree"": ""Master of Computer Science - MCS"", ""major"": ""Computer Science"", ""period"": ""2020 \u2013 2021""}, {""school"": ""Texas A&M University"", ""degree"": ""Bachelor of Science - BS"", ""major"": ""Major: Applied Mathematics - Minor: Computer Sience"", ""period"": ""2016 \u2013 2020""}]",Divergent Internship,"Testing And Software Engineer, Summer Intern",Jun 2021 – Sep 2021
7,7,"• Provided QA for team project’s new updates and supported c++ documentation through doxygen, breathe, exhale and sphinx.","[{""school"": ""UC Irvine"", ""degree"": ""Master of Computer Science - MCS"", ""major"": ""Computer Science"", ""period"": ""2020 \u2013 2021""}, {""school"": ""Texas A&M University"", ""degree"": ""Bachelor of Science - BS"", ""major"": ""Major: Applied Mathematics - Minor: Computer Sience"", ""period"": ""2016 \u2013 2020""}]",Divergent Internship,"Testing And Software Engineer, Summer Intern",Jun 2021 – Sep 2021
8,8,• Used Scala and Apache Spark to create and debug ETL jobs; improved data processing efficiency by 200%,"[{""school"": ""UC Irvine"", ""degree"": ""Master's degree"", ""major"": ""Master of Software Engineering"", ""period"": ""2021 \u2013 2022""}, {""school"": ""National Chiao Tung University"", ""degree"": ""Non-Degree Student"", ""major"": ""Computer Science"", ""period"": ""2019 \u2013 2019""}, {""school"": ""Fu Jen Catholic University"", ""degree"": ""Non-Degree Student"", ""major"": ""Information Management"", ""period"": ""2019 \u2013 2020""}]",SAGE Technologies Limited Full-time,Technical Consultant,May 2018 – Jul 2019
9,9,• Set up a data collection system using Python and Scrapy Framework to parse 15+ websites,"[{""school"": ""UC Irvine"", ""degree"": ""Master's degree"", ""major"": ""Master of Software Engineering"", ""period"": ""2021 \u2013 2022""}, {""school"": ""National Chiao Tung University"", ""degree"": ""Non-Degree Student"", ""major"": ""Computer Science"", ""period"": ""2019 \u2013 2019""}, {""school"": ""Fu Jen Catholic University"", ""degree"": ""Non-Degree Student"", ""major"": ""Information Management"", ""period"": ""2019 \u2013 2020""}]",SAGE Technologies Limited Full-time,Technical Consultant,May 2018 – Jul 2019

In [71]:
queries = ['python','software','distributed']
rows = []
for qid,query in enumerate(queries):
    qid += 1
    row = [str(qid), query]
    rows.append(row)
queris = pd.DataFrame(rows, columns=["qid", "query"])
queris[:10]

  qid        query
0  1   python
1  2   software
2  3   distributed

In [70]:
rows = []
for qid,query in enumerate(queries):
    qid += 1
    for docno in list( profiles['docno'] ):
        label = random.randint(0,5)
        iteration = random.randint(1,5)/2
        row = [str(qid),str(docno),int(label),str(iteration)]
        rows.append(row)
qrels = pd.DataFrame(rows, columns=["qid", "docno","label",'iteration'])
qrels[:10]

  qid docno  label iteration
0  1   0     0      0.5
1  1   1     2      2.5
2  1   2     3      0.5
3  1   3     3      1.5
4  1   4     4      1.5
5  1   5     1      0.5
6  1   6     4      1.5
7  1   7     3      1.0
8  1   8     1      1.5
9  1   9     1      2.5

In [24]:
pt_index_path = './resume_index'


### initialization 
if not pt.started():
    pt.init()

### load index fils to index obj
### If index fils are not existed, create index files by indexer
if not os.path.exists(pt_index_path + "/data.properties"):
    index_dir = pt_index_path
    indexer = pt.DFIndexer(index_dir, overwrite=True)
    index_ref = indexer.index(profiles["text"], profiles["docno"])

    ### load the index
    index = pt.IndexFactory.of(index_ref)
else:
    index = pt.IndexFactory.of(pt_index_path)

### show the stat 
print(index.getCollectionStatistics().toString())

### show the reverse index
#for kv in index.getLexicon():
#    print("%s -> %s" % (kv.getKey(), kv.getValue().toString() ) )
print(index.getLexicon()["python"])

Number of documents: 363
Number of terms: 1510
Number of postings: 4637
Number of fields: 0
Number of tokens: 4906
Field names: []
Positions:   false

term132 Nt=47 TF=48 maxTF=2 @{0 4369 1}

In [68]:
tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")
results = tfidf.search("python model nlp")
results[:10]

  qid  docid docno  rank     score             query
0  1   94     94    0     8.107563  python model nlp
1  1   303    303   1     5.110236  python model nlp
2  1   250    250   2     4.305174  python model nlp
3  1   238    238   3     3.938236  python model nlp
4  1   97     97    4     3.041413  python model nlp
5  1   201    201   5     2.966357  python model nlp
6  1   106    106   6     2.894916  python model nlp
7  1   270    270   7     2.894916  python model nlp
8  1   107    107   8     2.745723  python model nlp
9  1   59     59    9     2.503389  python model nlp

In [69]:
docids = list( results['docid'][:10] )
print(docids)
for docid in docids:
    print( profiles[ profiles['docno'] == str(docid)]['text'] )

[94, 303, 250, 238, 97, 201, 106, 270, 107, 59]
94    • Achieved industry benchmark in the NLP classification task using BERT model with python to conclude the project.
Name: text, dtype: object
303    • Developed various analytical models through Python
Name: text, dtype: object
250    • Developed automated process for identifying comments on Twitter with Python web crawler. Built an NLP pipeline using spaCy for text classification and tokenization and combined with Azure for sentiment analysis. Reduced processing time by 33%.
Name: text, dtype: object
238    - Classified victims and provided customized domestic violence support recommendations by building K-modes model in Python
Name: text, dtype: object
97    • Built pipelines in Python to run ensemble of customized learning models like CatBoost, support vector machine, neural networks etc. resulting in a common platform for all clients’ data.
Name: text, dtype: object
201    - Use Random Forest model to label the unlabeled data in the database for inferring the formula of calculating the CPI of Taiwan from 100,000,000+ everyday electronic invoice data with Python & PostgreSQL
Name: text, dtype: object
106    • Developed an automated system by designing APIs with Python, SQL, and Shell Script to facilitate other engineers’ model training processes, such as filtering, processing, and auto‑labeling data from the internal shared database
Name: text, dtype: object
270    • Implemented decision tree model through Python based on customers’ historical data with final recall ratio of 74% to find out potential insurance buyers and assist decision making of strategy team
Name: text, dtype: object
107    • Improved the accuracy of a multi‑class object detection model by 5% mAP compared to a previous model
Name: text, dtype: object
59    * Build investing strategy / model for trading room
Name: text, dtype: object

In [72]:
pt.Experiment(
    [tfidf],
    queris,
    qrels,
    eval_metrics=["map", "ndcg"])

         name       map      ndcg
0  BR(TF_IDF)  0.040297  0.087066